FROM node:20-bullseye

# Install build dependencies required for node-pty native compilation
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

EXPOSE 3000

RUN mkdir /workspace

CMD ["node","server.js"]