# ingress.yml = traffic router for your Services.

#   user
#     ↓
#  Ingress
#   ↙     ↘
# Service A  Service B
#   ↓          ↓
# Pods       Pods

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: codespace-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /api/sandbox
            pathType: Prefix
            backend:
              service:
                name: sandbox-service
                port:
                  number: 80
    - http:
        paths:
          - path: /api/ai
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  number: 80                  

    - host: "*.agent.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-service
                port:
                  number: 80

    - host: "*.preview.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-service
                port:
                  number: 80