# Service = gives those Pods(from deployment) a stable network endpoint
# sandbox.service.yml creates a Service in Kubernetes.
kind: Service
apiVersion: v1
metadata:
  name:  sandbox-service
spec:
  type: ClusterIP
  selector:
    app: sandbox
  ports:
  - name: main-sandbox-port
    port: 80
    targetPort: 3000